services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloud_storage-app
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_MINIO_USER: ${MINIO_USER}
      SPRING_MINIO_PASS: ${MINIO_PASS}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - minio
    networks:
      - app_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: cloud_storage-frontend
    ports:
      - "8090:80"
    networks:
      - app_net

  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console UI
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app_net

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app_net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    restart: always
    volumes:
      - redis_insight:/data
    networks:
      - app_net

volumes:
  postgres_data:
    name: postgres_data
  minio_data:
    name: minio_data
  redis_data:
    name: redis_data
  redis_insight:
    name: redis_insight

networks:
  app_net: