logging:
  level:
    org:
      springframework:
        cloud.vault: DEBUG
        security: DEBUG
        vault: DEBUG

minio:
  url: http://localhost:9000
#  access-key: ${spring.minio.access-key}
  access-key: minioadmin
#  secret-key: ${spring.minio.secret-key}
  secret-key: minioadmin
  bucket-name: user-files

spring:
  application:
    name: cloud-storage
#  profiles:
#    active: datasource, minio
#  config:
#    import: vault://
#
#  cloud:
#    compatibility-verifier:
#      enabled: false
#    vault:
#      uri: http://localhost:8200
#      token: root
#      authentication: TOKEN
#      kv:
#        enabled: true
#        backend: secret
#        default-context: cloud-storage
#        application-name: cloud-storage
#        profiles: datasource, minio
#      scheme: http

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB