logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: info

minio:
  url: http://minio:9000
  access-key: ${SPRING_MINIO_USER}
  secret-key: ${SPRING_MINIO_PASS}
  bucket-name: user-files

spring:
  application:
    name: cloud-storage

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  session:
    store-type: redis
  data:
    redis:
      host: redis
      port: 6379
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB