logging:
  level:
    org:
      springframework:
        cloud.vault: DEBUG
        security: DEBUG

minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: user-files

spring:
  application:
    name: cloud-storage

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  session:
    store-type: redis
  data:
    redis:
      host: redis
      port: 6379
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB